### ISSUE TITLE
URL for INSTALL.md

### ISSUE THREAD

**Issue by Veeraraju-E** [u2seg/U2Seg#11]
Hi!

You guys have put out some amazing work here!

Just wanted to let you know the URL for INSTALL.md (the one mentioned here - [home](https://github.com/u2seg/U2Seg/tree/main)) is missing. Please provide the installation guidelines.

Thanks!

**Comment by misobalogh** [comment]
U can find it in this commit:
https://github.com/u2seg/U2Seg/commit/2ad5e7e7dfa30981c71af12142e0b0dea33932e7

**Comment by Veeraraju-E** [comment]
Thank you!

**Comment by Veeraraju-E** [comment]
Closing issue as URL was found

**Comment by KaichengNi** [comment]
The file was deleted in that commit also

**Comment by kcniii** [comment]
It has also been deleted in that commit.

**Comment by luxuan1111** [comment]
Where can I find the installation documentation? Could you please provide it to me?
