### ISSUE TITLE
Cityscapes Val Resolution

### ISSUE THREAD

**Issue by ChristophReich1996** [u2seg/U2Seg#7]
Hi, 

thanks for sharing your validation code. However, one specific question, for me it is not 100% clear which resolution you utilize for validation on Cityscapes (panoptic segmentation). From the code, it seems that you are validating on the full resolution (2048 x 1024), is this correct? Have you also validated on other resolutions? I could imagine that a lower resolution could potentially lead to better results, due to the lower training resolution. Again thanks for your help!

Best,
Christoph

**Comment by Dantong88** [comment]
Yes, for evaluation on cityscapes, we **did not** do specific pre-processing before inserting it into our network. 
That means we just input the original images then do the inference, I remember the network will resize it automatilly to the training/evaluation size to align with the network, after inference it will be recovered by resize back, then calculate metric with grounf truth, as we say, our groud truth should be 2048 * 1024.

Not sure if low resolution will have better preformance, a tuition is it might help.
